### ISSUE TITLE
Does WebSocketConnection ping its clients?

### ISSUE THREAD

**Issue by bnjbvr** [http-rs/tide-websockets#11]
Hi! Thanks for making this project, it's great :)
I've been bitten hard by a nasty bug: when served behind a reverse proxy, namely nginx, nginx may forward the websocket requests, but will close them if the server doesn't send data for 60 seconds or more. This is a default value and it's configurable, however by skimming the websocket spec I've realized that it has a notion of ping/pong control frames, so the server can let the client (and conversely) know the connection is alive. I *don't think* it's automatically done by this middleware, so this raises a few questions:

- does the WebSocketConnection automatically handle incoming pings (from the client)?
- should it send regular pings, if it hasn't received any for the last N seconds?

I could even be convinced to implement this, if that was of interest :)

**Comment by jbr** [comment]
The middleware wraps async-tungstenite, which wraps tungstenite. Tungstenite does handle _replying_ to pings for us. I'm not sure if we should _send_ intermittent pings by default (or even by configuration), but I added a quick PR that allows user code to send them

**Comment by jbr** [comment]
Closing this, as #12 is in v0.3.0, allowing you to send [`Message::Ping`](https://docs.rs/tungstenite/0.13.0/tungstenite/enum.Message.html#variant.Ping) on whatever schedule is appropriate for your use case
