### ISSUE TITLE
0.2.0 on crates.io missing send()

### ISSUE THREAD

**Issue by minghuaw** [http-rs/tide-websockets#13]
Seems like the `send` function is not published on crates.io. There is no `send` when I looked at the source code on docs.rs
![Screen Shot 2021-02-06 at 9 03 34 PM](https://user-images.githubusercontent.com/29760666/107137202-f3e6db80-68be-11eb-8ec9-f4caf6be1f0d.png)

**Comment by jbr** [comment]
yes, that hasn't been released yet — it was just added earlier today. You can always use `tide-websockets = { git = "https://github.com/http-rs/tide-websockets", branch = "main" }` to use the latest before the next release.

Out of curiosity, what are you using it for? Ping?

**Comment by minghuaw** [comment]
> yes, that hasn't been released yet — it was just added earlier today. You can always use `tide-websockets = { git = "https://github.com/http-rs/tide-websockets", branch = "main" }` to use the latest before the next release.
> 
> Out of curiosity, what are you using it for? Ping?

Actually trying to send a Close message.

**Comment by jbr** [comment]
Oh interesting, hadn't considered that use case! I had been expecting clients would do the disconnection/closing generally, or that the server would just drop the websocket 
connection

**Comment by minghuaw** [comment]
> Oh interesting, hadn't considered that use case! I had been expecting clients would do the disconnection/closing generally, or that the server would just drop the websocket
> connection

Oh yeah, you are right. I didn't really think much about it. Guess I need some more coffee.
