### ISSUE TITLE
help ！Change closure to function

### ISSUE THREAD

**Issue by huyidao4444** [http-rs/tide-websockets#14]
I want change Change closure to function。

The code is as follows：

```rust
async fn main() -> Result<(), std::io::Error> {

    env_logger::init();

    let mut app = tide::new();

    app.at("ws/:target")

        .with(WebSocket::new(getws))

        .get(|_| async move { Ok("this was not a websocket request") });

    app.listen("127.0.0.1:8080").await?;

    Ok(())
}
```

```rust
async fn getws(request: Request<Arc<i32>>, mut stream: WebSocketConnection) -> ResultTide<()> {

    while let Some(Ok(Message::Text(input))) = stream.next().await {

        let output: String = input.chars().rev().collect();

        stream

            .send_string(format!("{} | {}", &input, &output))

            .await?;

    }

    Ok(())

}
```

It can't build 。Why ？

Looking forward to the answer.Thank

**Comment by pepoviola** [comment]
Hi @huyidao4444, thanks for report. Can you post here the error that you are getting.
Thx!

**Comment by huyidao4444** [comment]
Thank！
error is：
expected a `std::ops::Fn<(tide::Request<()>, tide::Next<'a, ()>)>` closure, found `tide_websockets::WebSocket<std::sync::Arc<i32>, fn(tide::Request<std::sync::Arc<i32>>, tide_websockets::WebSocketConnection) -> impl std::future::Future {getws}>`

expected an `Fn<(tide::Request<()>, tide::Next<'a, ()>)>` closure, found `tide_websockets::WebSocket<std::sync::Arc<i32>, fn(tide::Request<std::sync::Arc<i32>>, tide_websockets::WebSocketConnection) -> impl std::future::Future {getws}>`

help: the trait `for<'a> std::ops::Fn<(tide::Request<()>, tide::Next<'a, ()>)>` is not implemented for `tide_websockets::WebSocket<std::sync::Arc<i32>, fn(tide::Request<std::sync::Arc<i32>>, tide_websockets::WebSocketConnection) -> impl std::future::Future {getws}>`
note: required because of the requirements on the impl of `tide::Middleware<()>` for `tide_websockets::WebSocket<std::sync::Arc<i32>, fn(tide::Request<std::sync::Arc<i32>>, tide_websockets::WebSocketConnection) -> impl std::future::Future {getws}>`

Can you give me an example of WebSocket‘s handler using functions。

**Comment by jbr** [comment]
This isn't working because your tide server has a state of (), since you built it with tide::new(), but your handler is expecting a tide state of `Arc<i32>`. If you want tide to hold an `Arc<i32>`, you need to use [`tide::with_state(Arc::new(0i32))`](https://docs.rs/tide/0.16.0/tide/fn.with_state.html)` or similar. Or, alternatively, change your `Request<Arc<i32>>` to `Request<()>`

**Comment by huyidao4444** [comment]
This can work now.

I've just started learning trust. Thank you for your help！！！
