### ISSUE TITLE
Version 0.2.1 | 0.3.0 release?

### ISSUE THREAD

**Issue by thedodd** [http-rs/tide-websockets#16]
Hello there. We have recently adopted this project in [Trunk](https://github.com/thedodd/trunk) for our dev server proxy system, and we are using the feature introduced here by [abe4211113e16d38459fac43c688282bd8f41e90](https://github.com/http-rs/tide-websockets/tree/abe4211113e16d38459fac43c688282bd8f41e90).

Would you mind cutting a release so that we can go ahead and publish our [Trunk 0.9.0](https://github.com/thedodd/trunk/issues/140) release?

Thanks for all of the great work here! It works quite nicely!

**Comment by jbr** [comment]
Will do :thumbsup:

**Comment by jbr** [comment]
v0.3.0 published

**Comment by thedodd** [comment]
Woot woot! You rock @jbr, thx!
