### ISSUE TITLE
Implementing Sink for WebSocketConnection?

### ISSUE THREAD

**Issue by xosxos** [http-rs/tide-websockets#7]
Hello! Great to see websocket support come into fruition for Tide! I was playing around with the implementation. The basic functionality is looking good! This lead me to wonder if there are any future plans on implementing the Sink trait for WebSocketConnection?

**Comment by jbr** [comment]
See https://github.com/http-rs/tide-websockets/pull/3#issuecomment-748107203

**Comment by xosxos** [comment]
Ah sorry did not see that one! I am somewhat new to Rust so I get the basic sending and receiving to work but cant figure out how to emit messages to multiple clients in the way you can outlined in this blog post about Warp https://blog.logrocket.com/how-to-build-a-websocket-server-with-rust/

As a noobie I don't understand implementing async iteration both ways at the same time without splitting the stream :( And as this isn't stackoverflow I am not expecting a solution here but thank you for your time !

**Comment by xosxos** [comment]
Got it working now, just took a couple of hours more learning async rust !
